version: '3.9'

services:
  go-api:
    container_name: go-api
    image: go-api:1.0.0
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go-api-local
    volumes:
      - ./cmd/api:/usr/app

  go-api-local:
    container_name: go-api-local
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: go-api-local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
